### ISSUE TITLE
Python 3.8 in base container

### ISSUE THREAD

**Issue by cablespaghetti** [jthomperoo/custom-pod-autoscaler#121]
**Is your feature request related to a problem? Please describe.**
I noticed that the base container has python 3.6 and it's missing a few features included in 3.8. Is is possible to increase this? I couldn't find the Dockerfile or I'd make a PR.

**Comment by jthomperoo** [comment]
Hey thanks for the suggestion, yep that's a good idea, thinking in the interests of not breaking anything that already uses the python image maybe I could add in a few more images:

- `custompodautoscaler/python-3-6`
- `custompodautoscaler/python-3-7`
- `custompodautoscaler/python-3-8`

Thing is what to do with the existing `custompodautoscaler/python` image, I'm gonna have a look at the python 3.6 -> 3.8 changelogs and just check if there are any breaking changes listed, if there aren't I'll upgrade the `custompodautoscaler/python` to 3.8, otherwise I'm not entirely sure what to do with it.

Here's the Dockerfile by the way incase you're interested!
https://github.com/jthomperoo/custom-pod-autoscaler/blob/master/Dockerfile

**Comment by cablespaghetti** [comment]
Sounds good! I clearly wasn't awake yesterday to not see that Dockerfile :facepalm:

**Comment by jthomperoo** [comment]
So looking through the changelogs, the only breaking change I can see is:

> Backwards incompatible syntax changes:
> - async and await are now reserved keywords.

From the [Python 3.7](https://docs.python.org/3/whatsnew/3.7.html) changelog.

I think this is a small enough change to not be a major issue, if this affects anyone's autoscalers they can switch over to
`custompodautoscaler/python-3-6`.

**Comment by jthomperoo** [comment]
OK so those new images are now available in release `v1.0.1`.

There's [a docs page now that describes all supported Docker images](https://custom-pod-autoscaler.readthedocs.io/en/stable/reference/docker-images/) and [a new example that describes how to use a different Docker image (that may not be supported) with the Custom Pod Autoscaler](https://github.com/jthomperoo/custom-pod-autoscaler/tree/v1.0.1/example/custom-docker-image) allowing you to embed the binary into any Docker image you may need.

Thanks for suggesting these changes!
